module read_mars

contains

  SUBROUTINE GENOUT(VECTOR,NDIM,ALPHA,NUNIT,NP,MWRITE,NS)
    implicit none

    CHARACTER*6      ALPHA
    INTEGER          NP,MWRITE,I,MS,NS,NUNIT,NDIM,M5
    COMPLEX*16          VECTOR(NDIM,MEDIM)

    M5=MIN(5,MWRITE)
    DO MS=1,MWRITE
       WRITE(NUNIT,1010) ALPHA,RM(MS,NS),RN(NS)
       WRITE(NUNIT,1020) (VECTOR(I,MS),I=1,NP)
    END DO

1010 FORMAT(//,1X,A,2F20.0)
1020 FORMAT(2D30.15)
    RETURN
  END SUBROUTINE GENOUT


  SUBROUTINE read_mars
    implicit none

    INTEGER      MS,I,K
    CHARACTER*80 LINE
    
    INTEGER         NEG,NEGEIG,NIT,NXDEV,NYDEV,NXPNEG,NYPNEG          
    INTEGER         NEV, M, N, MY
    COMMON /AUXINT/ NEG,NEGEIG,NIT,NXDEV,NYDEV,NXPNEG,NYPNEG          
    $               ,NEV, M, N, MY

    IF (.NOT.OUTDAT) GOTO 20
    OPEN(CHOUTP,FILE='OUTDATA',FORM='FORMATTED')
    REWIND(CHOUTP)
    WRITE(CHOUTP,NEWRUN)
    WRITE(CHOUTP,1000) NRP1,MSMAX,NSMAX
    WRITE(CHOUTP,1010) ALNORM
    DO MS=1,MSMAX
       WRITE(CHOUTP,1020) MS,RM(MS,2),RN(2)
    END DO
    WRITE(CHOUTP,1030) (CSV(I),I=1,NRP1)

    CALL GENOUT(V1U,NTP1,'   V1U',CHOUTP,NRP1  ,MSMAX,2)
    CALL GENOUT(V2U,NTP1,'   V2U',CHOUTP,NR    ,MSMAX,2)
    CALL GENOUT(V3U,NTP1,'   V3U',CHOUTP,NR    ,MSMAX,2)
    CALL GENOUT(B1U,NTP1,'   B1U',CHOUTP,NTP1  ,MSMAX,2)
    CALL GENOUT(B2U,NTP1,'   B2U',CHOUTP,NTP1-1,MSMAX,2)
    CALL GENOUT(B3U,NTP1,'   B3U',CHOUTP,NTP1-1,MSMAX,2)
    CALL GENOUT(J1U,NTP1,'   J1U',CHOUTP,NTP1-1,MSMAX,2)
    CALL GENOUT(J2U,NTP1,'   J2U',CHOUTP,NTP1  ,MSMAX,2)
    CALL GENOUT(J3U,NTP1,'   J3U',CHOUTP,NTP1  ,MSMAX,2)
    CALL GENOUT(PRE,NTP1,'   PRE',CHOUTP,NR    ,MSMAX,2)
    CALL GENOUT(PPERP,NTP1,' PPERP',CHOUTP,NR  ,MSMAX,2)
    CALL GENOUT(PPARA,NTP1,' PPARA',CHOUTP,NR  ,MSMAX,2)
    CALL GENOUT(X1U,NTP1,'   X1U',CHOUTP,NRP1  ,MSMAX,2)
    CALL GENOUT(X2U,NTP1,'   X2U',CHOUTP,NR    ,MSMAX,2)
    CALL GENOUT(X3U,NTP1,'   X3U',CHOUTP,NR    ,MSMAX,2)
       
    CLOSE(CHOUTP)

    ! OUTPUT DENSITY AND RESISTIVITY PROFILES AGAINST CS AND CSV
    
    IF (.NOT.LPROFI) GOTO 20
    OPEN(CHMAP,FILE='MAP',FORM='FORMATTED')
    REWIND(CHMAP)
    WRITE(CHMAP,1050) NRP1,(CS(I),CSV(I),RHO(I),RESIST(I),I=1,NRP1)
    CLOSE(CHMAP)
    WRITE(*,1050)     NRP1,(CS(I),CSV(I),RHO(I),RESIST(I),I=1,NRP1)
    
20  CONTINUE
    !----------------------------------------
    ! CYQLIU 15/04/1999
    IF (INCFEED.GE.0) CALL FEEDOUT
    ! CYQLIU 18/03/2003
    CALL TTORQUE
    ! CYQLIU 12/05/2003
    CALL PPVISC
    ! ----------------------------------------
    OPEN(CHDONE,FILE='DONE',FORM='FORMATTED')
    REWIND(CHDONE)
    WRITE(CHDONE,NEWRUN)
    WRITE(CHDONE,1000) NRP1,MSMAX,NSMAX
    WRITE(CHDONE,1010) ALNORM
    !
    !     LIST EIGENVALUE
    !
    OPEN(CHLIST,FILE='RESULT',FORM='FORMATTED')
    IF (NPARAM.LE.1) GOTO 40
    DO I = 2,NPARAM
       READ(CHLIST,'(A)',END=40) LINE
    END DO
40  CONTINUE
    IF (INCFEED.EQ.1.OR.INCFEED.EQ.11.OR.INCFEED.EQ.12.OR. &
         INCFEED.EQ.3.OR.INCFEED.EQ.5.OR.INCFEED.EQ.9) THEN
       WRITE(CHLIST,1045) GAINA(1),GAINP(1),PSITS,ALNORM
    ENDIF
    IF (INCFEED.EQ.0) THEN
       WRITE(CHLIST,1045) GAINA(1),FLOAT(NIT),AL0,ALNORM
    ENDIF
    IF (INCFEED.EQ.2.OR.INCFEED.EQ.4.OR.INCFEED.EQ.10) THEN
       WRITE(CHLIST,1045) RLK(1),RMFS(1),AL0,ALNORM
    ENDIF
    CLOSE(CHLIST)
    
    ! OUTPUT FEEDBACK CURRENTS AND SENSOR SIGNALS
    OPEN(CHLIST,FILE='CURRSENS',FORM='FORMATTED')
    IF (NPARAM.LE.1) GOTO 60
    DO I = 2,NPARAM
       DO K=1,NCOIL
          READ(CHLIST,'(A)',END=60) LINE
       ENDDO
    ENDDO
60  CONTINUE
    DO K=1,NCOIL
       WRITE(CHLIST,1045) GAINA(K),GAINP(K),OFEEDI(K),OSENSR(K),OSENSP(K)
    ENDDO
    CLOSE(CHLIST)
    
    ! --- OUTPUT THE PERTURBED PLASMA CURRENT, FOR CARIDDI INPUT
    OPEN(CHOUTP,FILE='JPLASMA')
    REWIND(CHOUTP)
    WRITE(CHOUTP,1171) MSMAX,NTP1,RNTOR,0,0,0
    DO MS=1,MSMAX
       WRITE(CHOUTP,1172) RM(MS,2),RM(MS,2),RM(MS,2), &
            RM(MS,2),RM(MS,2),RM(MS,2)
    ENDDO
    DO MS=1,MSMAX
       DO II=1,NTP1
          WRITE(CHOUTP,1172) REAL(J1U(II,MS)),IMAG(J1U(II,MS)), &
               REAL(J2U(II,MS)),IMAG(J2U(II,MS)), &
               REAL(J3U(II,MS)),IMAG(J3U(II,MS))
       ENDDO
    ENDDO
    CLOSE(CHOUTP)
1171 FORMAT(I5,1X,I5,1X,E9.2,3(1X,I2))
1172 FORMAT(E16.8,5(1X,E16.8))
    
    !     --- OUTPUT THE PERTURBED MAGNETIC FIELD, FOR VISUALIZATION
    OPEN(CHOUTP,FILE='BPLASMA')
    REWIND(CHOUTP)
    IF (ABS(RM(MS,2)).GT.0.1.OR.ABS(RNTOR).GT.1.0E-13) THEN
       WRITE(CHOUTP,1171) MSMAX,NTP1,RNTOR,0,0,0
    ELSE
       WRITE(CHOUTP,1171) MSMAX-1,NTP1,RNTOR,0,0,0
    ENDIF
    DO MS=1,MSMAX
       IF (ABS(RM(MS,2)).GT.0.1.OR.ABS(RNTOR).GT.1.0E-13) THEN
          WRITE(CHOUTP,1172) RM(MS,2),RM(MS,2),RM(MS,2), &
               RM(MS,2),RM(MS,2),RM(MS,2)
       ENDIF
    ENDDO
    DO MS=1,MSMAX
       IF (ABS(RM(MS,2)).GT.0.1.OR.ABS(RNTOR).GT.1.0E-13) THEN
          DO II=1,NTP1
             WRITE(CHOUTP,1172) REAL(B1U(II,MS)),IMAG(B1U(II,MS)), &
                  REAL(B2U(II,MS)),IMAG(B2U(II,MS)), &
                  REAL(B3U(II,MS)),IMAG(B3U(II,MS))
          ENDDO
       ENDIF
    ENDDO
    CLOSE(CHOUTP)
    
    !     --- OUTPUT THE PERTURBED VELOCITY, FOR VISUALIZATION
    OPEN(CHOUTP,FILE='VPLASMA')
    REWIND(CHOUTP)
    IF (ABS(RM(MS,2)).GT.0.1.OR.ABS(RNTOR).GT.1.0E-13) THEN
       WRITE(CHOUTP,1171) MSMAX,NRP1,RNTOR,0,0,0
    ELSE
       WRITE(CHOUTP,1171) MSMAX-1,NRP1,RNTOR,0,0,0
    ENDIF
    DO MS=1,MSMAX
       IF (ABS(RM(MS,2)).GT.0.1.OR.ABS(RNTOR).GT.1.0E-13) THEN
          WRITE(CHOUTP,1172) RM(MS,2),RM(MS,2),RM(MS,2), &
               RM(MS,2),RM(MS,2),RM(MS,2)
       ENDIF
    ENDDO
    DO II=1,NRP1
       WRITE(CHOUTP,1172) DPSIDS(II),DPSIDS(II),DPSIDS(II), &
            T(II),T(II),T(II)
    ENDDO
    DO MS=1,MSMAX
       IF (ABS(RM(MS,2)).GT.0.1.OR.ABS(RNTOR).GT.1.0E-13) THEN
          DO II=1,NRP1
             WRITE(CHOUTP,1172) REAL(X1U(II,MS)),IMAG(X1U(II,MS)), &
                  REAL(X2U(II,MS)),IMAG(X2U(II,MS)), &
                  REAL(X3U(II,MS)),IMAG(X3U(II,MS))
          ENDDO
       ENDIF
    ENDDO
    CLOSE(CHOUTP)
    
    !     --- OUTPUT THE PERTURBED PLASMA PRESSURES, FOR VISUALIZATION
    OPEN(CHOUTP,FILE='PPLASMA')
    REWIND(CHOUTP)
    WRITE(CHOUTP,1171) MSMAX,NRP1,RNTOR,0,0,0
    DO MS=1,MSMAX
       WRITE(CHOUTP,1172) RM(MS,2),RM(MS,2),RM(MS,2), &
            RM(MS,2),RM(MS,2),RM(MS,2)
    ENDDO
    DO MS=1,MSMAX
       DO II=1,NRP1
          WRITE(CHOUTP,1172) REAL(PRE(II,MS)),IMAG(PRE(II,MS)), &
               REAL(PPERP(II,MS)),IMAG(PPERP(II,MS)), &
               REAL(PPARA(II,MS)),IMAG(PPARA(II,MS))
       ENDDO
    ENDDO
    CLOSE(CHOUTP)
    
    !     --- OUTPUT THE JACOBIAN
    OPEN(CHOUTP,FILE='JACOBIAN')
    REWIND(CHOUTP)
    WRITE(CHOUTP,1171) MSMAX,NTP1
    DO MS=1,MSMAX
       WRITE(CHOUTP,1172) RM(MS,2),RM(MS,2)
    ENDDO
    DO MS=1,MSMAX
       DO II=1,NTP1
          WRITE(CHOUTP,1172) REAL(JACOBI(II,MS)), &
               IMAG(JACOBI(II,MS))
       ENDDO
    ENDDO
    CLOSE(CHOUTP)
    
    RETURN
    
1000 FORMAT(3I20)
1010 FORMAT(///,2D30.15,//)
1020 FORMAT(I20,2F20.5)
1030 FORMAT(///,(2D30.15))
1040 FORMAT(1P,3X,E13.5,3X,2E13.5,3X,2E13.5)
1045 FORMAT(1P,E10.2,E13.5,2E13.5,2E13.5,2E13.5)
1050 FORMAT(I5,/,(3F20.10,E20.5))
  END SUBROUTINE read_mars

end module read_mars
